site_name: Libmg Docs

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_bases: true
            show_source: true
            show_root_heading: false
            show_root_toc_entry: false
            members_order: source
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            merge_init_into_class: true
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Libmg Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - Code Reference: reference/
  - explanation.md