# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        poetry install --with tests --with docs
    - name: Lint with flake8
      run: |
        poetry run flake8 libmg
    - name: Type check with mypy
      run: |
        poetry run mypy libmg
    - name: Test with pytest
      run: |
        poetry run pytest
    - name: Update docs
      run: |
        poetry run mkdocs build
        poetry run mkdocs gh-deploy --force
